@baseUrl = http://localhost:5206
@productId = 2779ee47-10b0-4bd7-8342-404006aa1392


GET {{baseUrl}}/api/products/{{productId}}

###v1
GET {{baseUrl}}/api/products/{{productId}}
api-version: 1

###v1
GET {{baseUrl}}/api/products/{{productId}}
api-version:2